In [39]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix

In [40]:
from google.colab import files
uploaded = files.upload()

Saving sheet.csv to sheet (1).csv


In [41]:
import pandas as pd
df = pd.read_csv ('sheet.csv')
print (df)

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]


In [42]:
df = pd.read_csv ('sheet.csv')
df.rename(columns={'User ID' :'Gender', 'Age':'Age', 
                          'Estimated Salary':'EstimatedSalary', 'Purchased':'Purchased'}, inplace=True)

df = df.apply(LabelEncoder().fit_transform)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Gender           400 non-null    int64
 1   Gender           400 non-null    int64
 2   Age              400 non-null    int64
 3   EstimatedSalary  400 non-null    int64
 4   Purchased        400 non-null    int64
dtypes: int64(5)
memory usage: 15.8 KB


In [43]:
X = df.iloc[:, :4].values
y = df.iloc[:, -1].values

print("First 5 features :\n", X[:5])
print("First 5 labels :\n", y[:5])

First 5 features :
 [[ 97   1   1   4]
 [392   1  17   5]
 [155   0   8  26]
 [ 64   0   9  39]
 [382   1   1  57]]
First 5 labels :
 [0 0 0 0 0]


In [44]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=12, shuffle=True)

print("Total train features {} and the labels {}".format(len(X_train), len(y_train)))
print("Total test features {} and the labels {}".format(len(X_test), len(y_test)))

Total train features 320 and the labels 320
Total test features 80 and the labels 80


In [45]:
X_train = StandardScaler().fit_transform(X_train)
X_test = StandardScaler().fit_transform(X_test)

In [46]:
classifier = GaussianNB().fit(X_train, y_train)

In [47]:
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_pred, y_test)

score_test = classifier.score(X_test, y_test)
score_train = classifier.score(X_train, y_train)

cm_dict = {"Positive":cm[:, 0], "Negative":cm[:, 1]}

cm_df = pd.DataFrame(cm_dict, index=['True', 'False'])

print("The classifier have {}% accuracy on test data".format(round(score_test*100)))
print("The classifier have {}% accuracy on train data".format(round(score_train*100)))
print("\nConfusion Matrix :\n\n", cm_df)

The classifier have 88% accuracy on test data
The classifier have 91% accuracy on train data

Confusion Matrix :

        Positive  Negative
True         44         6
False         4        26
